/* DO NOT EDIT THIS FILE - it is machine generated */
#include <jni.h>
/* Header for class net_telesing_tsdk_tlib_Acomms */

#ifndef _Included_net_telesing_tsdk_tlib_Acomms
#define _Included_net_telesing_tsdk_tlib_Acomms
#ifdef __cplusplus
extern "C" {
#endif
/*
 * Class:     net_telesing_tsdk_tlib_Acomms
 * Method:    bindCer
 * Signature: (Ljava/lang/String;I)I
 */
JNIEXPORT jint JNICALL Java_net_telesing_tsdk_tlib_Acomms_bindCer
  (JNIEnv *, jobject, jstring, jint);

/*
 * Class:     net_telesing_tsdk_tlib_Acomms
 * Method:    unbindCer
 * Signature: (Ljava/lang/String;I)I
 */
JNIEXPORT jint JNICALL Java_net_telesing_tsdk_tlib_Acomms_unbindCer
  (JNIEnv *, jobject, jstring, jint);

/*
 * Class:     net_telesing_tsdk_tlib_Acomms
 * Method:    isBindCer
 * Signature: (Ljava/lang/String;I)I
 */
JNIEXPORT jint JNICALL Java_net_telesing_tsdk_tlib_Acomms_isBindCer
  (JNIEnv *, jobject, jstring, jint);

/*
 * Class:     net_telesing_tsdk_tlib_Acomms
 * Method:    getSectionsStatus
 * Signature: (Ljava/lang/String;)I
 */
JNIEXPORT jint JNICALL Java_net_telesing_tsdk_tlib_Acomms_getSectionsStatus
  (JNIEnv *, jobject, jstring);

/*
 * Class:     net_telesing_tsdk_tlib_Acomms
 * Method:    genrWave
 * Signature: (Ljava/lang/String;Ljava/lang/String;)[S
 */
JNIEXPORT jshortArray JNICALL Java_net_telesing_tsdk_tlib_Acomms_genrWave
  (JNIEnv *, jobject, jstring, jstring);

/*
 * Class:     net_telesing_tsdk_tlib_Acomms
 * Method:    startRecog
 * Signature: (Lnet/telesing/tsdk/tlib/Recog_cfg;)I
 */
JNIEXPORT jint JNICALL Java_net_telesing_tsdk_tlib_Acomms_startRecog
  (JNIEnv *, jobject, jobject);

/*
 * Class:     net_telesing_tsdk_tlib_Acomms
 * Method:    pauseRecog
 * Signature: ()I
 */
JNIEXPORT jint JNICALL Java_net_telesing_tsdk_tlib_Acomms_pauseRecog
  (JNIEnv *, jobject);

/*
 * Class:     net_telesing_tsdk_tlib_Acomms
 * Method:    restartRecog
 * Signature: ()I
 */
JNIEXPORT jint JNICALL Java_net_telesing_tsdk_tlib_Acomms_restartRecog
  (JNIEnv *, jobject);

/*
 * Class:     net_telesing_tsdk_tlib_Acomms
 * Method:    stopRecog
 * Signature: ()I
 */
JNIEXPORT jint JNICALL Java_net_telesing_tsdk_tlib_Acomms_stopRecog
  (JNIEnv *, jobject);

/*
 * Class:     net_telesing_tsdk_tlib_Acomms
 * Method:    stopRecog
 * Signature: ()I
 */
JNIEXPORT jint JNICALL Java_net_telesing_tsdk_tlib_Acomms_initRecog
  (JNIEnv *, jobject);

/*
 * Class:     net_telesing_tsdk_tlib_Acomms
 * Method:    writeRecog
 * Signature: ([SI)I
 */
JNIEXPORT jint JNICALL Java_net_telesing_tsdk_tlib_Acomms_writeRecog
  (JNIEnv *, jobject, jshortArray, jint);

/*
 * Class:     net_telesing_tsdk_tlib_Acomms
 * Method:    setRecogConfig
 * Signature: (Lnet/telesing/tsdk/tlib/Recog_cfg;)I
 */
JNIEXPORT jint JNICALL Java_net_telesing_tsdk_tlib_Acomms_setRecogConfig
  (JNIEnv *, jobject, jobject);

/*
 * Class:     net_telesing_tsdk_tlib_Acomms
 * Method:    getRecogConfig
 * Signature: ()Lnet/telesing/tsdk/tlib/Recog_cfg;
 */
JNIEXPORT jobject JNICALL Java_net_telesing_tsdk_tlib_Acomms_getRecogConfig
  (JNIEnv *, jobject);

/*
 * Class:     net_telesing_tsdk_tlib_Acomms
 * Method:    getRecogStatus
 * Signature: ()Lnet/telesing/tsdk/tlib/Recog_status;
 */
JNIEXPORT jobject JNICALL Java_net_telesing_tsdk_tlib_Acomms_getRecogStatus
  (JNIEnv *, jobject);


/*
* Class:     net_telesing_jni_demo_JNIDemo
* Method:    getWord
* Signature: ()V
*/
JNIEXPORT jint JNICALL Java_net_telesing_jni_demo_JNIDemo_getWord
(JNIEnv *, jobject);


#ifdef __cplusplus
}
#endif
#endif
